name: Run Tests

on: pull_request

jobs:
  code:
    name: Test code
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Get Yarn cache
      uses: c-hive/gha-yarn-cache@v1

    - name: Install dependencies
      run: yarn

    - name: Run tests
      run: yarn test:coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
